---
title: "01_cleaning_browse_data"
author: "anne"
date: "31 oktober 2018"
output: word_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
load("processdata/browse.rda")
load("processdata/browse_sub.rda")
```

## Cleaning data
```{r}
class(browse)
str(browse)
head(browse, n = 3)
names(browse)

str(browse_sub)
head(browse_sub, n = 3)
names(browse-sub)

```

Create a subset of browse with less variables
```{r}
browse_sub  <- browse[,c(1:5,7:9,15:24,27:45,51,59,61:67,69,74,76:83,85,87:90,92:97,99:105,108:122)]
head(browse_sub, n = 3)

save(browse_sub, file = "browse_sub.rda")


load("processdata/browse_sub.rda")
head(browse_sub)
names(browse_sub)
```



##### change column names, structure (numeric, integer, factor), and level names for factors
```{r}
# new column


# col. names

# colnames(fdata1)[colnames(fdata1)=="ï..ID"] <- "ID"


# structure 
browse_sub$FYLNR <- as.integer(browse_sub$FYLNR)
browse_sub$KOMNR <- as.integer(browse_sub$KOMNR)
browse_sub$elgbROSprs10 <- as.numeric(browse_sub$elgbROSprs10)
browse_sub$elgbFURUprs10 <- as.numeric(browse_sub$elgbFURUprs10)
browse_sub$elgbBJORKprs10 <- as.numeric(browse_sub$elgbBJORKprs10)
browse_sub$ROS_0_PRHA <- as.integer(browse_sub$ROS_0_PRHA)
browse_sub$ROS_0_25_PRHA <- as.integer(browse_sub$ROS_0_25_PRHA)
browse_sub$ROS_25_49_PRHA <- as.integer(browse_sub$ROS_25_49_PRHA)
browse_sub$Bjork_0_PRHA <- as.integer(browse_sub$Bjork_0_PRHA)
browse_sub$Bjork_0_25_PRHA <- as.integer(browse_sub$Bjork_0_25_PRHA)
browse_sub$Bjork_25_49_PRHA <- as.integer(browse_sub$Bjork_25_49_PRHA)
browse_sub$elgFURUha10 <- as.numeric(browse_sub$elgFURUha10)
browse_sub$elgROSha10 <- as.numeric(browse_sub$elgROSha10)
browse_sub$elgBJORKha10 <- as.numeric(browse_sub$elgBJORKha10)
browse_sub$elgLAUVha10 <- as.numeric(browse_sub$elgLAUVha10)
browse_sub$treartgruppe <- as.factor(browse_sub$treartgruppe)
browse_sub$skogkategori <- as.factor(browse_sub$skogkategori)
browse_sub$kant <- as.factor(browse_sub$kant)
browse_sub$region <- as.factor(browse_sub$region)
browse_sub$landsdel <- as.factor(browse_sub$landsdel)
browse_sub$tretetthet0 <- as.numeric(browse_sub$tretetthet0)
browse_sub$tretetthet025 <- as.numeric(browse_sub$tretetthet025)
browse_sub$tretetthet2549 <- as.numeric(browse_sub$tretetthet2549)
browse_sub$tretetthetpluss50 <- as.numeric(browse_sub$tretetthetpluss50)
browse_sub$tretetthetminus25 <- as.numeric(browse_sub$tretetthetminus25)

```



## Subsetting

Subset of "browse_sub" (several) on 9th and 10th takst
```{r}
browse_910 <- split(browse_sub, browse_sub$takst)

browse_9 <- browse_910[['9']]
browse_10 <- browse_910[['10']]


save(browse_9, file = "browse_9.rda")
save(browse_10, file = "browse_10.rda")

# just temporary until I get back info on variables from Erling
browse_9 <- browse_9[,c(1:8,47:48,57:82,88:89)]
browse_91 <- browse_9[,c(1:8,10,12:15,24,27:28,32:36)]

```

Creating subsets for different data
```{r}

browse2000 <- browse_sub[browse_sub$disthouse < 2001, ] # longest distance to house 2000m
browse1500 <- browse_sub[browse_sub$distroad500 < 1501, ] # longest distance to any road (that is further than 500m from a house) 1500m
browse1500pub <- browse_sub[browse_sub$distpubroad500 < 1501, ] # longest distance to public roads (that are further than 500m from a house) 1500m

browseros <- browse2000[browse2000$treegroup=="raw", ]
browserosdistroad <- browse1500[browse1500$treegroup=="raw", ]
browserosdistpubroad <- browse1500pub[browse1500pub$treegroup=="raw", ]



browse2000 <- browse_sub[browse_sub$disthouse < 2001, ] # longest distance to house 2000m
browse1500 <- browse_sub[browse_sub$distroad500 < 1501, ] # longest distance to any road (that is further than 500m from a house) 1500m
# browse1500pub <- browse_sub[browse_sub$distpubroad500 < 1501, ] # longest distance to public roads (that are further than 500m from a house) 1500m

browseroad1500 <- browse_sub[browse_sub$distroad1 < 1501, ]
broad1500house500 <- browse_sub[which(browse_sub$distroad1 < 1501 & browse_sub$disthouse > 499), ]

browse9_dist <- browse_9[which(browse_9$distvei1 < 1501 & browse_9$disthus > 499), ] # longest distance to any road (that is further than 500m from a house) 1500m
browse10_dist <- browse_10[which(browse_10$distvei1 < 1501 & browse_10$disthus > 499), ] # longest distance to any road (that is further than 500m from a house) 1500m

browse9_dist2 <- browse_9[which(browse_9$distvei1 < 1501 & browse_9$disthus > 499 & browse_9$elgbROSprs9 < 101), ] # longest distance to any road (that is further than 500m from a house) 1500m and browsingpressure is under 101%

# browseros <- browse2000[browse2000$treegroup=="raw", ]
# browserosdistroad <- browse1500[browse1500$treegroup=="raw", ]
# browserosdistpubroad <- browse1500pub[browse1500pub$treegroup=="raw", ]

names(browseroad1500)
head(broad1500house500)

save(browseroad1500, file = "browseroad1500.rda")

```



## For browse_9

##### Explore NAs 
```{r}

nrow(browse_91)
nrow(na.omit(browse_91))

head(browse_9, n = 10)
tail(browse_9, n = 10)
# unique(unlist(lapply(browse_9, function (x) which(is.na(x)))))
# fdata1[102, ]

# browse_9$distvei1[is.na(browse_9$distvei1)] <- 10000
# browse_9$distvei2[is.na(browse_9$distvei2)] <- 10000
# browse_9$distvei3[is.na(browse_9$distvei3)] <- 10000

browse_91 <- na.omit(browse_91)

save(browse_91, file = "browse_91.rda")
load("browse_91.rda")

```

##### Data structure -> factor levels
```{r}

ggplot(data = browse_91, aes(landsdel)) +
  geom_bar()+
  theme_classic()

ggplot(data = browse_91, aes(skogkategori)) +
  geom_bar()+
  theme_classic()

ggplot(data = browse_91, aes(kant)) +
  geom_bar()+
  theme_classic()

ggplot(data = browse_91, aes(treartgruppe)) +
  geom_bar()+
  theme_classic()

ggplot(data = browse_91, aes(hohkatb)) +
  geom_bar()+
  theme_classic()

ggplot(data = browse_91, aes(region)) +
  geom_bar()+
  theme_classic()

```

```{r}
browse_91$beitetrykkr <- round(browse_91$beitetrykk)
```

```{r}
browse_91$landsdel <- as.factor(browse_91$landsdel)
browse_91$hohkatb <- as.factor(browse_91$hohkatb)
browse_91$landsdel <- factor(browse_91$landsdel, levels = c("Østlandet-Øst", "Midt-Norge", "Nord-Norge", "Sørlandet", "Vestlandet", "Østlandet-vest"))
browse_91$skogkategori <- factor(browse_91$skogkategori, levels = c("Lavproduktiv_eldreskog", "Høyproduktiv_eldreskog", "Høyproduktiv_ungskog",  "Lavproduktiv_ungskog", "Uproduktiv_skog"))
browse_91$kant <- factor(browse_91$kant, levels = c("kant >20m", "kant <10m", "kant 10-20m", "mangler kant")) 
browse_91$treartgruppe <- factor(browse_91$treartgruppe, levels = c("LAUV", "BJORK", "FURU", "ROS"))
browse_91$hohkatb <- factor(browse_91$hohkatb, levels = c("200", "0", "100", "300", "400", "500", "600", "700", "800"))
browse_91$region <- factor(browse_91$region, levels = c("Hedmark", "Agder", "Buskerud", "Hordaland", "More og Romsdal", "Nord-Trondelag", "Nordland", "Oppland", "Ostfold-Akershus", "Rogaland", "Sogn og Fjordane", "Sor-Trondelag", "Troms", "Vestfold-Telemark"))

```






















