---
title: "01_cleaning_browse_data_BP"
author: "anne"
date: "15 januar 2020"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# For browse9.2 (for browsing pressure response)

##### Data structure -> factor levels

```{r}
load("processdata/browse9.1.rda")
load("processdata/browse9.2.rda")
```


```{r}

str(browse0.1)
head(browse0.1, n = 3)
names(browse0.1)

```

##### Subsetting on 9th and 10th cycle
```{r}
browse0.1_910 <- split(browse0.1, browse0.1$takst)

browse9.1 <- browse0.1_910[['9']]
# browse10.1 <- browse0.1_910[['10']]
summary(browse9.1)

save(browse9.1, file = "browse9.1.rda")
# save(browse_10, file = "browse_10.rda")
load("processdata/browse9.1.rda")

browse9.1 <- browse9.1[,c(1:5,7:9,15:24,34:36,40:45,51,59,62:67,74,76:79,88:90,99:105,112:115)]
browse9.2 <- browse9.1
browse9.3 <- subset(browse9.3, select = -c(9:27))
browse9.3 <- subset(browse9.3, select = -c(11:16, 18:21))
# browse9.2$x <- NULL
summary(browse9.2)

browse9.5 <- browse9.1
browse9.5 <- browse9.5[,c(1:3,5:8,19:24,36,41,43,48,50:53)]

```


##### Explore NAs 
```{r}

nrow(browse9.2)
nrow(na.omit(browse9.2))

nrow(browse9.3)
nrow(na.omit(browse9.3))

# head(browse_9, n = 10)
# tail(browse_9, n = 10)
# sum(unique(unlist(lapply(browse9.3, function (x) which(is.na(x))))))
# fdata1[102, ]

browse9.3 <- browse9.2[,c(1:3,5,7:9,88:90,102:105,112:115,126:131)]

sum(is.na(browse9.3$beitetrykk9))
sum(is.na(browse9.3$tretetthet9))

browse9.2$distvei1[is.na(browse9.2$distvei1)] <- 10000
browse9.2$distvei2[is.na(browse9.2$distvei2)] <- 10000
browse9.2$distvei3[is.na(browse9.2$distvei3)] <- 10000
browse9.2$disthus[is.na(browse9.2$disthus)] <- 10000


browse9.3$distvei1[is.na(browse9.3$distvei1)] <- 10000
browse9.3$distvei2[is.na(browse9.3$distvei2)] <- 10000
browse9.3$distvei3[is.na(browse9.3$distvei3)] <- 10000
browse9.3$disthus[is.na(browse9.3$disthus)] <- 10000

browse9.2 <- na.omit(browse9.2)
browse9.3 <- na.omit(browse9.3)
# 
# save(browse9.2, file = "browse9.2.rda")
load("processdata/browse9.2.rda")


```


```{r}
library(ggplot2)
# ggplot(data = browse9bro_dist, aes(landsdel)) +
#   geom_bar()+
#   theme_classic()

ggplot(data = browse9.2, aes(skogkategori)) +
  geom_bar()+
  theme_classic()

ggplot(data = browse9.2, aes(kant)) +
  geom_bar()+
  theme_classic()

ggplot(data = browse9.4, aes(treartgruppe9)) +
  geom_bar()+
  theme_classic()

# ggplot(data = browse9.2, aes(treartgruppe)) +
#   geom_bar()+
#   theme_classic()

# ggplot(data = browse9bro_dist, aes(hohkatb)) +
#   geom_bar()+
#   theme_classic()

ggplot(data = browse9.2, aes(region)) +
  geom_bar()+
  theme_classic()

ggplot(data = browse9.3, aes(vegetasjon)) +
  geom_bar()+
  theme_classic()

ggplot(data = browse9.2_dist, aes(veitype2)) +
  geom_bar()+
  theme_classic()

ggplot(data = browse9.2_dist, aes(veitype3)) +
  geom_bar()+
  theme_classic()


```

```{r}

browse9.2$beitetrykkr <- as.integer(round(browse9.2$beitetrykk9))
browse9.2$bt100 <- browse9.2$beitetrykkr/100
```

```{r}
# browse9.2$landsdel <- as.factor(browse9.2$landsdel)
# browse9.2$hohkatb <- as.factor(browse9.2$hohkatb)
# browse9.2$landsdel <- factor(browse9.2$landsdel, levels = c("Sørlandet", "Østlandet-Øst", "Midt-Norge", "Nord-Norge", "Vestlandet", "Østlandet-vest"))
browse9.2$skogkategori <- factor(browse9.2$skogkategori, levels = c("Lavproduktiv_eldreskog", "Høyproduktiv_eldreskog", "Høyproduktiv_ungskog",  "Lavproduktiv_ungskog", "Uproduktiv_skog"))
browse9.2$kant <- factor(browse9.2$kant, levels = c("kant >20m", "kant <10m", "kant 10-20m", "mangler kant")) 
browse9.2$treartgruppe <- factor(browse9.2$treartgruppe9, levels = c("LAUV", "FURU", "ROS"))
# browse9.2$hohkatb <- factor(browse9.2$hohkatb, levels = c("100", "0", "200", "300", "400", "500", "600", "700", "800"))
browse9.2$region <- factor(browse9.2$region, levels = c("Hedmark", "Agder", "Buskerud", "Hordaland",  "More og Romsdal", "Nord-Trondelag", "Nordland", "Oppland", "Ostfold-Akershus", "Rogaland", "Sogn og Fjordane", "Sor-Trondelag", "Troms", "Vestfold-Telemark"))

browse9.2_dist$veitype2 <- as.character(browse9.2_dist$veitype2)
browse9.2_dist$veitype2[browse9.2_dist$veitype2 == ""] <- "europaogriksveg"
browse9.2_dist$veitype2 <- factor(browse9.2_dist$veitype2, levels = c("privatveg", "europaogriksveg", "fylkesveg", "kommuneveg"))


```

```{r}
save(browse9.2, file = "browse9.2.rda")
save(browse9.2_dist, file = "browse9.2_dist.rda")
load("processdata/browse9.2.rda")
```


##### Subset
```{r}

# subset on disthus and distvei2 > 3000
# browse9.3 <- browse9.2[ which(browse9.2$disthus < 3000 & browse9.2$distvei2 < 3000),]
# save(browse9.3, file = "browse9.3.rda")
# 
# browse_9$disthus_cut210 <- ifelse(browse_9$disthus >= 210, 210, browse_9$disthus)
# 
# browse_9_dist <- browse_9[browse_9$distvei1 > 200, ] # longest distance to any public road 1500m
# head(browse_9_dist)
# save(browse_9_dist, file = "browse_9_dist.rda")
# 
# browse_9_distbin <- browse_9[browse_9$disthus > 200, ] 
# browse_9_distbeta <- browse_9[browse_9$disthus > 210, ] 
# # head(browse_9_dist)
# save(browse_9_distbin, file = "browse_9_distbin.rda")
# save(browse_9_distbeta, file = "browse_9_distbeta.rda")



browse9.2$disthus_trunc <- ifelse(browse9.2$disthus >= 3000, 3000, browse9.2$disthus)
browse9.2$distvei2_trunc <- ifelse(browse9.2$distvei2 >= 2218, 2218, browse9.2$distvei2)
browse9.2$tretetthet9_trunc <- ifelse(browse9.2$tretetthet9 >= 3960, 3960, browse9.2$tretetthet9)


# browse9.2_dist$disthus_trunc <- ifelse(browse9.2_dist$disthus >= 3000, 3000, browse9.2_dist$disthus)
# browse9.2_dist$distvei2_trunc <- ifelse(browse9.2_dist$distvei2 >= 3000, 3000, browse9.2_dist$distvei2)
# browse9.2_dist$tretetthet9_trunc <- ifelse(browse9.2_dist$tretetthet9 >= 3960, 3960, browse9.2_dist$tretetthet9)

browse9.2_distnew <- browse9.2[ which(browse9.2$disthus > 200), ]
head(browse9.2_dist)



save(browse9.2_dist, file = "browse9.2_dist.rda")

```

##### threshold cuts disthus
```{r}
browse9.2$disthus_cut1000 <- ifelse(browse9.2$disthus >= 1000, 1000, browse9.2$disthus)
browse9.2$disthus_cut950 <- ifelse(browse9.2$disthus >= 950, 950, browse9.2$disthus)
browse9.2$disthus_cut900 <- ifelse(browse9.2$disthus >= 900, 900, browse9.2$disthus)
browse9.2$disthus_cut850 <- ifelse(browse9.2$disthus >= 850, 850, browse9.2$disthus)
browse9.2$disthus_cut800 <- ifelse(browse9.2$disthus >= 800, 800, browse9.2$disthus)
browse9.2$disthus_cut750 <- ifelse(browse9.2$disthus >= 750, 750, browse9.2$disthus)
browse9.2$disthus_cut700 <- ifelse(browse9.2$disthus >= 700, 700, browse9.2$disthus)
browse9.2$disthus_cut650 <- ifelse(browse9.2$disthus >= 650, 650, browse9.2$disthus)
browse9.2$disthus_cut600 <- ifelse(browse9.2$disthus >= 600, 600, browse9.2$disthus)
browse9.2$disthus_cut500 <- ifelse(browse9.2$disthus >= 500, 500, browse9.2$disthus)
browse9.2$disthus_cut400 <- ifelse(browse9.2$disthus >= 400, 400, browse9.2$disthus)
browse9.2$disthus_cut300 <- ifelse(browse9.2$disthus >= 300, 300, browse9.2$disthus)
browse9.2$disthus_cut200 <- ifelse(browse9.2$disthus >= 200, 200, browse9.2$disthus)
browse9.2$disthus_cut150 <- ifelse(browse9.2$disthus >= 150, 150, browse9.2$disthus)
browse9.2$disthus_cut175 <- ifelse(browse9.2$disthus >= 175, 175, browse9.2$disthus)
browse9.2$disthus_cut160 <- ifelse(browse9.2$disthus >= 160, 160, browse9.2$disthus)
browse9.2$disthus_cut190 <- ifelse(browse9.2$disthus >= 190, 190, browse9.2$disthus)
browse9.2$disthus_trunc_cut1000 <- ifelse(browse9.2$disthus_trunc >= 1000, 1000, browse9.2$disthus_trunc)
browse9.2$disthus_trunc_cut900 <- ifelse(browse9.2$disthus_trunc >= 900, 900, browse9.2$disthus_trunc)
browse9.2$disthus_trunc_cut800 <- ifelse(browse9.2$disthus_trunc >= 800, 800, browse9.2$disthus_trunc)
browse9.2$disthus_trunc_cut700 <- ifelse(browse9.2$disthus_trunc >= 700, 700, browse9.2$disthus_trunc)
browse9.2$disthus_trunc_cut600 <- ifelse(browse9.2$disthus_trunc >= 600, 600, browse9.2$disthus_trunc)
browse9.2$disthus_trunc_cut500 <- ifelse(browse9.2$disthus_trunc >= 500, 500, browse9.2$disthus_trunc)
browse9.2$disthus_trunc_cut400 <- ifelse(browse9.2$disthus_trunc >= 400, 400, browse9.2$disthus_trunc)
browse9.2$disthus_trunc_cut300 <- ifelse(browse9.2$disthus_trunc >= 300, 300, browse9.2$disthus_trunc)
browse9.2$disthus_trunc_cut200 <- ifelse(browse9.2$disthus_trunc >= 200, 200, browse9.2$disthus_trunc)
browse9.2$disthus_trunc_cut150 <- ifelse(browse9.2$disthus_trunc >= 150, 150, browse9.2$disthus_trunc)
browse9.2$disthus_trunc_cut175 <- ifelse(browse9.2$disthus_trunc >= 175, 175, browse9.2$disthus_trunc)
browse9.2$disthus_trunc_cut160 <- ifelse(browse9.2$disthus_trunc >= 160, 160, browse9.2$disthus_trunc)
browse9.2$disthus_trunc_cut190 <- ifelse(browse9.2$disthus_trunc >= 190, 190, browse9.2$disthus_trunc)
browse9.2$disthus_trunc_cut100 <- ifelse(browse9.2$disthus_trunc >= 100, 100, browse9.2$disthus_trunc)



```



##### Scale variables
```{r}

browse9.2$HOH_scale = scale(browse9.2$HOH)
browse9.2$tretetthet9_scale = scale(browse9.2$tretetthet9)
browse9.2$helling_scale = scale(browse9.2$helling)
browse9.2$disthus_scale = scale(browse9.2$disthus)
browse9.2$distvei2_scale = scale(browse9.2$distvei2)
browse9.2$ac_scale = scale(browse9.2$ac)
browse9.2$disthus_cut1000_scale = scale(browse9.2$disthus_cut1000)
browse9.2$disthus_cut900_scale = scale(browse9.2$disthus_cut900)
browse9.2$disthus_cut800_scale = scale(browse9.2$disthus_cut800)
browse9.2$disthus_cut700_scale = scale(browse9.2$disthus_cut700)
browse9.2$disthus_cut600_scale = scale(browse9.2$disthus_cut600)
browse9.2$disthus_cut500_scale = scale(browse9.2$disthus_cut500)
browse9.2$disthus_cut400_scale = scale(browse9.2$disthus_cut400)
browse9.2$disthus_cut300_scale = scale(browse9.2$disthus_cut300)
browse9.2$disthus_cut200_scale = scale(browse9.2$disthus_cut200)
browse9.2$disthus_cut150_scale = scale(browse9.2$disthus_cut150)
browse9.2$disthus_cut175_scale = scale(browse9.2$disthus_cut175)
browse9.2$disthus_cut160_scale = scale(browse9.2$disthus_cut160)
browse9.2$disthus_cut190_scale = scale(browse9.2$disthus_cut190)
browse9.2$disthus_trunc_cut1000_scale = scale(browse9.2$disthus_trunc_cut1000)
browse9.2$disthus_trunc_cut900_scale = scale(browse9.2$disthus_trunc_cut900)
browse9.2$disthus_trunc_cut800_scale = scale(browse9.2$disthus_trunc_cut800)
browse9.2$disthus_trunc_cut700_scale = scale(browse9.2$disthus_trunc_cut700)
browse9.2$disthus_trunc_cut600_scale = scale(browse9.2$disthus_trunc_cut600)
browse9.2$disthus_trunc_cut500_scale = scale(browse9.2$disthus_trunc_cut500)
browse9.2$disthus_trunc_cut400_scale = scale(browse9.2$disthus_trunc_cut400)
browse9.2$disthus_trunc_cut300_scale = scale(browse9.2$disthus_trunc_cut300)
browse9.2$disthus_trunc_cut200_scale = scale(browse9.2$disthus_trunc_cut200)
browse9.2$disthus_trunc_cut150_scale = scale(browse9.2$disthus_trunc_cut150)
browse9.2$disthus_trunc_cut175_scale = scale(browse9.2$disthus_trunc_cut175)
browse9.2$disthus_trunc_cut160_scale = scale(browse9.2$disthus_trunc_cut160)
browse9.2$disthus_trunc_cut190_scale = scale(browse9.2$disthus_trunc_cut190)
browse9.2$tretetthet9_trunc_scale = scale(browse9.2$tretetthet9_trunc)
browse9.2$distvei2_trunc_scale = scale(browse9.2$distvei2_trunc)
browse9.2$disthus_trunc_scale = scale(browse9.2$disthus_trunc)
browse9.2$disthus_trunc_cut100_scale = scale(browse9.2$disthus_trunc_cut100)


browse9.2_dist$tretetthet9_trunc_scale = scale(browse9.2_dist$tretetthet9_trunc)
browse9.2_dist$distvei2_trunc_scale = scale(browse9.2_dist$distvei2_trunc)
browse9.2_dist$disthus_trunc_scale = scale(browse9.2_dist$disthus_trunc)
browse9.2_dist$helling_scale = scale(browse9.2_dist$helling)
browse9.2_dist$helling_scale <- browse9.2_dist$helling_scale
browse9.2_dist$helling_scale <- NULL

browse9.3$HOH_scale = scale(browse9.3$HOH)
browse9.3$tretetthet9_scale = scale(browse9.3$tretetthet9)
browse9.3$helling_scale = scale(browse9.3$helling)
browse9.3$disthus_scale = scale(browse9.3$disthus)
browse9.3$distvei2_scale = scale(browse9.3$distvei2)
browse9.3$ac_scale = scale(browse9.3$ac)
browse9.3$disthus_cut1000_scale = scale(browse9.3$disthus_cut1000)
browse9.3$disthus_cut950_scale = scale(browse9.3$disthus_cut950)
browse9.3$disthus_cut900_scale = scale(browse9.3$disthus_cut900)
browse9.3$disthus_cut850_scale = scale(browse9.3$disthus_cut850)
browse9.3$disthus_cut800_scale = scale(browse9.3$disthus_cut800)
browse9.3$disthus_cut750_scale = scale(browse9.3$disthus_cut750)
browse9.3$disthus_cut700_scale = scale(browse9.3$disthus_cut700)
browse9.3$disthus_cut650_scale = scale(browse9.3$disthus_cut650)

save(browse9.2, file = "browse9.2.rda")
save(browse9.2_distnew, file = "browse9.2_distnew.rda")

```


## New dataset with only variables we use in the models
```{r}
browse9.4_house <- browse9.2[,c(8,10,12,17,19:21,23:25,35,49,92)]
browse9.4_house[,"disthus"] <- NULL
browse9.4_house[,"HOH"] <- NULL
browse9.4_house[,"tretetthet9"] <- NULL
browse9.4_house$tretetthet9_trunc <- browse9.2$tretetthet9_trunc
browse9.4_house$KOMNR <- browse9.2$KOMNR
browse9.4_house$treartgruppe9 <- factor(browse9.4_house$treartgruppe9, levels = c("LAUV", "FURU", "ROS"))



save(browse9.4_house, file = "browse9.4_house.rda")
browse9.4 <- browse9.2_dist[,c(3,10,12,17,19:23,25,35,36,49,69,92,97)]
browse9.4 <- subset(browse9.4, select = -c(4:5,9,12))
browse9.4$tretetthet9_trunc <- browse9.2_dist$tretetthet9_trunc
browse9.4[,"beitetrykk9"] <- NULL
browse9.4$beitetrykkr <- browse9.2_dist$beitetrykkr
browse9.4[,"tretetthet9_trunc_scale"] <- NULL

browse9.4$treartgruppe9 <- factor(browse9.4$treartgruppe9, levels = c("LAUV", "FURU", "ROS"))

save(browse9.4, file = "browse9.4.rda")




```

#### run the final models with final datset (only variables that are in the model)
```{r}

## house
m1kbin2 <- glmer(factor(beitetrykkr > 0) ~ disthus_trunc_cut200_scale + log(distvei2+1) + skogkategori + treartgruppe9 + ac_scale + kant + helling + HOH_scale + I(HOH_scale^2) + tretetthet9_trunc + (1|KOMNR),
            family = binomial(),
            data = browse9.4_house)
save(m1kbin2, file = "m1kbin2.rda")
load("output/m1kbin2.rda")


m1ibeta2 <- glmmTMB(bt100 ~ disthus_trunc_cut200_scale + log(distvei2+1) + skogkategori + treartgruppe9 + ac_scale + kant + helling + HOH_scale + I(HOH_scale^2) + tretetthet9_trunc + (1|KOMNR),
            data = browse9.4_house_pos,
            family = beta_family())
save(m1ibeta2, file = "m1ibeta2.rda")
load("output/m1ibeta2.rda")



## Roads
m4abin2 <- glmer(factor(beitetrykkr > 0) ~ log(distvei2_trunc+1) + skogkategori + treartgruppe9 + ac_scale + kant + helling + HOH_scale + I(HOH_scale^2) + tretetthet9_trunc + (1|KOMNR),
            family = binomial(),
            data = browse9.4)
load("output/m4abin2.rda")


m4abeta2 <- glmmTMB(bt100 ~ log(distvei2_trunc+1) + skogkategori + treartgruppe9 + ac_scale + kant + helling + HOH_scale + I(HOH_scale^2) + tretetthet9_trunc + (1|KOMNR),
            data = browse9.4pos,
            family = beta_family())
load("output/m4abeta2.rda")

```

