---
title: "09_total_path_effect"
author: "anne"
date: "29 august 2019"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Load data and models
```{r}
load("processdata/browse9.4.rda")
load("processdata/browse9.4_house.rda")
```

```{r}
library(lme4)
library(glmmTMB)
```


## Browsing pressure
#### Houses
```{r}
load("output/m1kbin2.rda")
zeromod1 <- m1kbin2

load("output/m1ibeta2.rda")
percmod1 <- m1ibeta2

load("processdata/browse9.4_house.rda")
dat1 <- browse9.4_house
```

#### Roads
```{r}
load("output/m4abin2.rda")
zeromod1 <- m4abin2
# summary(zeromod1)

load("output/m4abeta2.rda")
percmod1 <- m4abeta2 
# summary(percmod1)

load("processdata/browse9.4.rda")
# head(browse9.4)
dat1 <- browse9.4
```



## Recruits
#### Houses
```{r}
load("output/mhusabin.rda")
zeromod2 <- mhusabin

load("output/m16abeta.rda")
percmod2 <- m16abeta

load("processdata/browse9.5msc.rda")
dat2 <- browse9.5msc

```

#### Roads
```{r}
load("output/m16cbin.rda")
zeromod2 <- m16cbin
# summary(zeromod2)

load("output/m16abeta.rda")
percmod2 <- m16abeta
# summary(percmod2)

load("processdata/browse9.6sc.rda")
# head(browse9.6sc)
dat2 <- browse9.6sc
```




## Load and run function
```{r}
source("function_resp_curve.R")
```

```{r}
(focal = c("distvei", "skogkategori", "treartgruppe", "kant", 
           "helling", "HOH", "tretetthet", "browspres_merged", "disthus")[9])

```

#### Run function for the different models/ focals and SAVE them
```{r}
bp_tretett <- resp_curve(focal, dat1, dat2, zeromod1, percmod1, zeromod2, percmod2, 
           which_effect=c("hurdle1_only", "hurdle2_only", "total")[1], nvals=100, plotit=F, nb_btstrp=99)

recruit_beite <- resp_curve(focal, dat1, dat2, zeromod1, percmod1, zeromod2, percmod2, 
           which_effect=c("hurdle1_only", "hurdle2_only", "total")[2], nvals=100, plotit=F, nb_btstrp=99)

total_disthus <- resp_curve(focal, dat1, dat2, zeromod1, percmod1, zeromod2, percmod2, 
           which_effect=c("hurdle1_only", "hurdle2_only", "total")[3], nvals=100, plotit=F, nb_btstrp=99)
```

#### Save function data!
```{r}
save(total_disthus, file = "total_disthus.rda")
```




## load function data
```{r}
# Browsing pressure
load("output/final_function_outputs/bp_disthus.rda")
load("output/final_function_outputs/bp_distvei.rda")
load("output/final_function_outputs/bp_skogkat.rda")
load("output/final_function_outputs/bp_kant.rda")
load("output/final_function_outputs/bp_treart.rda")
load("output/final_function_outputs/bp_hell.rda")
load("output/final_function_outputs/bp_hoh.rda")
load("output/final_function_outputs/bp_tretett.rda")

# Recruits
load("output/final_function_outputs/recruit_disthus.rda")
load("output/final_function_outputs/recruit_distvei.rda")
load("output/final_function_outputs/recruit_skogkat.rda")
load("output/final_function_outputs/recruit_kant.rda")
load("output/final_function_outputs/recruit_treart.rda")
load("output/final_function_outputs/recruit_hell.rda")
load("output/final_function_outputs/recruit_beite.rda")
load("output/final_function_outputs/recruit_hoh.rda")

# Total
load("output/final_function_outputs/total_disthus.rda")
load("output/final_function_outputs/total_distvei.rda")
load("output/final_function_outputs/total_skogkat.rda")
load("output/final_function_outputs/total_kant.rda")
load("output/final_function_outputs/total_treart.rda")
load("output/final_function_outputs/total_hell.rda")
load("output/final_function_outputs/total_beite.rda")
load("output/final_function_outputs/total_tretett.rda")
load("output/final_function_outputs/total_hoh.rda")


```


## Re-scale
```{r}
# attributes(browse9.2$HOH_scale)
# attributes(browse9.2$disthus_trunc_cut200_scale)
# 
# d$s.x * attr(d$s.x, 'scaled:scale') + attr(d$s.x, 'scaled:center')


bp_disthus$var <- bp_disthus$var * 27.71453 + 192.2636
recruit_disthus$var <- recruit_disthus$var * 27.71453 + 192.2636
total_disthus$var <- total_disthus$var * 27.71453 + 192.2636


bp_distvei$var <- exp(bp_distvei$var)-1

bp_hoh$var <- bp_hoh$var * 244.7748 + 361.8423


recruit_distvei$var <- exp(recruit_distvei$var)-1

recruit_hoh$var <- recruit_hoh$var * 244.7748 + 361.8423


total_distvei$var <- exp(total_distvei$var)-1

total_hoh$var <- total_hoh$var * 244.7748 + 361.8423

```





## Plots
```{r}
library(ggplot2)

pt_disthus <- ggplot() + 
  geom_line(data = total_disthus, aes(var, point, color = "total"), linetype = 1, size = 1, show.legend = T) +
  geom_ribbon(data = total_disthus, aes(x = var, ymin = CI025, ymax = CI975), colour = "#004949", linetype = 2, alpha = 0.2) +
  geom_line(data = recruit_disthus, aes(var, point, color = "direct"), linetype = 1, size = 1, show.legend = T) +
  geom_ribbon(data = recruit_disthus, aes(x = var, ymin = CI025, ymax = CI975), colour = "#004949", linetype = 2, alpha = 0.2) +
  xlab("\nDistance to house (m)") + 
  ylab("Recruits (%)\n") +
  theme_light()+
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(family = "sans", size = 14, color = "grey30")) +
  scale_color_manual(name = "Effect on \nRecruits (%)", 
                     values = c("total" = "#009292", "direct" = "#004949"))

ph_disthus <- ggplot(data = bp_disthus, aes(var, point)) +
  geom_line(colour = "#009292", linetype = 1, size = 1)+
  geom_ribbon(aes(ymin = CI025, ymax = CI975), colour = "#004949", linetype = 2, alpha = 0.2) +
  theme_light() +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(family = "sans", size = 14, color = "grey30")) +
  xlab("\nDistance to house (m)") + 
  ylab("Browsing pressure (%)\n") +
  scale_y_continuous(limits = c(10, 25), breaks =  seq(from = 10, to = 25, by = 5))

pt_distvei <- ggplot() + 
  geom_line(data = total_distvei, aes(var, point, color = "total"), linetype = 1, size = 1, show.legend = T) +
  geom_ribbon(data = total_distvei, aes(x = var, ymin = CI025, ymax = CI975), colour = "#004949", linetype = 2, alpha = 0.2) +
  geom_line(data = recruit_distvei, aes(var, point, color = "direct"), linetype = 1, size = 1, show.legend = T) +
  geom_ribbon(data = recruit_distvei, aes(x = var, ymin = CI025, ymax = CI975), colour = "#004949", linetype = 2, alpha = 0.2) +
  xlab("\nDistance to road (m)") + 
  ylab("Recruits (%)\n") +
  theme_light()+
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(family = "sans", size = 14, color = "grey30")) +
  scale_color_manual(name = "Effect on \nRecruits (%)", 
                     values = c("total" = "#009292", "direct" = "#004949"))

ph_distvei <- ggplot(data = bp_distvei, aes(var, point)) +
  geom_line(colour = "#009292", linetype = 1, size = 1)+
  geom_ribbon(aes(ymin = CI025, ymax = CI975), colour = "#004949", linetype = 2, alpha = 0.2) +
  theme_light() +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(family = "sans", size = 14, color = "grey30")) +
  xlab("\nDistance to road (m)") + 
  ylab("Browsing pressure (%)\n") +
  scale_y_continuous(limits = c(10, 30), breaks =  seq(from = 10, to = 30, by = 5))


pt_skogkat <- ggplot() +
  geom_pointrange(data = total_skogkat, aes(x = var, y = point, ymin = CI025, ymax = CI975, colour = "total"), size = 1) +
  geom_pointrange(data = recruit_skogkat, aes(x = var, y = point, ymin = CI025, ymax = CI975, colour = "direct"), size = 1) +
  theme_light() +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(family = "sans", size = 14, color = "grey30")) +
  xlab("\nForest category") + 
  ylab("Recruits (%)\n") +
  scale_x_discrete(labels = c("Highproductive \nold forest", "Highproductive \nyoung forest", "Lowproductive \nold forest", "Lowproductive \nyoung forest", "Unproductive \nforest"))+
  scale_color_manual(name = "Effect on \nRecruits (%)", 
                     values = c("total" = "#009292", "direct" = "#004949"))

ph_skogkat <- ggplot(data = bp_skogkat,aes(var, point)) +
  geom_pointrange(aes(ymin = CI025, ymax = CI975), colour = "#009292", size = 1) +
  theme_light() +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(family = "sans", size = 14, color = "grey30")) +
  xlab("\nForest category") + 
  ylab("Browsing pressure (%)\n") +
  scale_x_discrete(labels = c("Highproductive \nold forest", "Highproductive \nyoung forest", "Lowproductive \nold forest", "Lowproductive \nyoung forest", "Unproductive \nforest"))+
  scale_y_continuous(limits = c(5, 50), breaks =  seq(from = 5, to = 50, by = 10))


pt_treart <- ggplot() +
  geom_pointrange(data = total_treart, aes(x = var, y = point, ymin = CI025, ymax = CI975, colour = "total"), size = 1) +
  geom_pointrange(data = recruit_treart, aes(x = var, y = point, ymin = CI025, ymax = CI975, colour = "direct"), size = 1) +
  theme_light() +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(family = "sans", size = 14, color = "grey30")) +
  xlab("\nTree species group") + 
  ylab("Recruits (%)\n") +
  scale_x_discrete(labels = c("Pine", "Other deciduous \ntrees", "Rowan, aspen, \nwillow")) +
  scale_color_manual(name = "Effect on \nRecruits (%)", 
                     values = c("total" = "#009292", "direct" = "#004949"))

ph_treart <- ggplot(data = bp_treart,aes(var, point)) +
  geom_pointrange(aes(ymin = CI025, ymax = CI975), colour = "#009292", size = 1) +
  theme_light() +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(family = "sans", size = 14, color = "grey30")) +
  xlab("\nTree species groups") + 
  ylab("Browsing pressure (%)\n") +
  scale_x_discrete(labels = c("Pine", "Other deciduous \ntrees", "Rowan, aspen, \nwillow")) +
  scale_y_continuous(limits = c(5, 50), breaks =  seq(from = 5, to = 50, by = 10))


pt_kant <- ggplot() +
  geom_pointrange(data = total_kant, aes(x = var, y = point, ymin = CI025, ymax = CI975, colour = "total"), size = 1) +
  theme_light() +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(family = "sans", size = 14, color = "grey30")) +
  xlab("\nEdge effect") + 
  ylab("Recruits (%)\n") +
  scale_x_discrete(labels = c("Edge <10m", "Edge >20m", "Edge 10-10m", "Edge information\nmissing")) +
  scale_color_manual(name = "Effect on \nRecruits (%)", 
                     values = c("total" = "#009292", "direct" = "#004949"))

ph_kant <- ggplot(data = bp_kant, aes(var, point)) +
  geom_pointrange(aes(ymin = CI025, ymax = CI975), colour = "#009292", size = 1) +
  theme_light() +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(family = "sans", size = 14, color = "grey30")) +
  xlab("\nEdge effect") + 
  ylab("Browsing pressure (%)\n") +
  scale_x_discrete(labels = c("Edge <10m", "Edge >20m", "Edge 10-10m", "Edge information\nmissing"))+
  scale_y_continuous(limits = c(5, 50), breaks =  seq(from = 5, to = 50, by = 10))


pt_hell <- ggplot() + 
  geom_line(data = total_hell, aes(var, point, color = "total"), linetype = 1, size = 1, show.legend = T) +
  geom_ribbon(data = total_hell, aes(x = var, ymin = CI025, ymax = CI975), colour = "#004949", linetype = 2, alpha = 0.2) +
  geom_line(data = recruit_hell, aes(var, point, color = "direct"), linetype = 1, size = 1, show.legend = T) +
  geom_ribbon(data = recruit_hell, aes(x = var, ymin = CI025, ymax = CI975), colour = "#004949", linetype = 2, alpha = 0.2) +
  xlab("\nSlope (%)") + 
  ylab("Recruits (%)\n") +
  theme_light()+
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(family = "sans", size = 14, color = "grey30")) +
  scale_color_manual(name = "Effect on \nRecruits (%)", 
                     values = c("total" = "#009292", "direct" = "#004949"))

ph_hell <- ggplot(data = bp_hell,aes(var, point)) +
  geom_line(colour = "#009292", linetype = 1, size = 1)+
  geom_ribbon(aes(ymin = CI025, ymax = CI975), colour = "#004949", linetype = 2, alpha = 0.2) +
  theme_light() +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(family = "sans", size = 14, color = "grey30")) +
  xlab("\nSlope (%)") + 
  ylab("Browsing pressure (%)\n")+
  scale_y_continuous(limits = c(10, 30), breaks =  seq(from = 10, to = 30, by = 5))


pt_hoh <- ggplot() + 
  geom_line(data = total_hoh, aes(var, point, color = "total"), linetype = 1, size = 1, show.legend = T) +
  geom_ribbon(data = total_hoh, aes(x = var, ymin = CI025, ymax = CI975), colour = "#004949", linetype = 2, alpha = 0.2) +
  geom_line(data = recruit_hoh, aes(var, point, color = "direct"), linetype = 1, size = 1, show.legend = T) +
  geom_ribbon(data = recruit_hoh, aes(x = var, ymin = CI025, ymax = CI975), colour = "#004949", linetype = 2, alpha = 0.2) +
  xlab("\nAltitude (%)") + 
  ylab("Recruits (%)\n") +
  theme_light()+
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(family = "sans", size = 14, color = "grey30")) +
  scale_color_manual(name = "Effect on \nRecruits (%)", 
                     values = c("total" = "#009292", "direct" = "#004949"))

ph_hoh <- ggplot(data = bp_hoh,aes(var, point)) +
  geom_line(colour = "#009292", linetype = 1, size = 1)+
  geom_ribbon(aes(ymin = CI025, ymax = CI975), colour = "#004949", linetype = 2, alpha = 0.2) +
  theme_light() +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(family = "sans", size = 14, color = "grey30")) +
  xlab("\nAltitude (m)") + 
  ylab("Browsing pressure (%)\n")+
  scale_y_continuous(limits = c(10, 30), breaks =  seq(from = 10, to = 30, by = 5))


pt_tretett <- ggplot() + 
  geom_line(data = total_tretett, aes(var, point, color = "indirect"), linetype = 1, size = 1, show.legend = T) +
  geom_ribbon(data = total_tretett, aes(x = var, ymin = CI025, ymax = CI975), colour = "#004949", linetype = 2, alpha = 0.2) +
  xlab("\nTree density (%)") + 
  ylab("Recruits (%)\n") +
  theme_light()+
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(family = "sans", size = 14, color = "grey30")) +
  scale_color_manual(name = "Effect on \nRecruits (%)", 
                     values = c("indirect" = "#009292"))


ph_tretett <- ggplot(data = bp_tretett,aes(var, point)) +
  geom_line(colour = "#009292", linetype = 1, size = 1)+
  geom_ribbon(aes (ymin = CI025, ymax = CI975), colour = "#004949", linetype = 2, alpha = 0.2) +
  theme_light() +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(family = "sans", size = 14, color = "grey30")) +
  xlab("\nTree density") + 
  ylab("Browsing pressure (%)\n")+
  scale_y_continuous(limits = c(10, 30), breaks =  seq(from = 10, to = 30, by = 5))


pt_beite <- ggplot() + 
  geom_line(data = total_beite, aes(var, point, color = "total"), linetype = 1, size = 1, show.legend = T) +
  geom_ribbon(data = total_beite, aes(x = var, ymin = CI025, ymax = CI975), colour = "#004949", linetype = 2, alpha = 0.2)+ 
  geom_line(data = recruit_beite, aes(var, point, color = "direct"), linetype = 1, size = 1, show.legend = T) +
  geom_ribbon(data = recruit_beite, aes(x = var, ymin = CI025, ymax = CI975), colour = "#004949", linetype = 2, alpha = 0.2) +
  xlab("\nBrowsing pressure (%)") + 
  ylab("Recruits (%)\n") +
  theme_light()+
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(family = "sans", size = 14, color = "grey30")) +
  scale_color_manual(name = "Effect on \nRecruits (%)", 
                     values = c("total" = "#009292", "direct" = "#004949"))


```
#### Plotgrid
```{r}
# library(cowplot)
# plot_grid(p1, p2, p3, p4, p5, p6, p7, p8,
#           nrow = 3, ncol = 3)

library(gridExtra)
grid.arrange(ph_treart, ph_disthus, ph_distvei, ph_hell, ph_hoh, ph_kant, ph_skogkat,  ph_tretett,
          nrow = 4, ncol = 2)

grid.arrange(pt_disthus, pt_distvei, pt_beite, pt_treart, pt_skogkat, pt_hell, pt_hoh, pt_kant, pt_tretett,
          nrow = 5, ncol = 2)

```



"#004949", "#009292"
